server:
    port: 8099
    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: TRACE

spring:
    datasource:
        name: test
        url: jdbc:mysql://115.159.75.208:3306/test
        username: root
        password: 12263520
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .html
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: me.remin.entity
    mapper-locations: classpath:mapper/*.xml

#通用mapper的配置
mapper:
    mappers:
        - me.remin.mapper.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql